/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Guru;

import Koneksi.koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
//import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MasGer
 */
public class formGuru extends javax.swing.JInternalFrame {

    /**
     * Creates new form formGuru
     */
    public formGuru() {
        initComponents();
    }
    
    public void tampilGuru(){
        Object[] row = {"NIP", "Nama Lengkap", "Jenis Kelamin", "Alamat", "Tanggal Lahir"}; 
        DefaultTableModel tabmodel = new DefaultTableModel(null,row);
        tblGuru.setModel(tabmodel); 
        
        koneksi sambung = new koneksi();
        try{
            String sql = "SELECT nip,nama_guru,jk,alamat,tanggal_lahir FROM guru";
            ResultSet res = sambung.stat.executeQuery(sql);
            while(res.next()){
                String nip = res.getString("nip");
                String nama_guru = res.getString("nama_guru");
                String jk = res.getString("jk");
                String alamat = res.getString("alamat");
                Date tanggal_lahir = res.getDate("tanggal_lahir");
                Object[] data = {nip,nama_guru,jk,alamat,tanggal_lahir};
                tabmodel.addRow(data);
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Koneksi Gagal "+e.toString());
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCariguru = new javax.swing.JTextField();
        cariGuru = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGuru = new javax.swing.JTable();
        refreshGuru = new javax.swing.JButton();
        tambahGuru = new javax.swing.JButton();
        hapusGuru = new javax.swing.JButton();
        editGuru = new javax.swing.JButton();
        tutupGuru = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA GURU");

        cariGuru.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cariGuru.setText("CARI");
        cariGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariGuruActionPerformed(evt);
            }
        });

        tblGuru.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGuru.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblGuruComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tblGuru);

        refreshGuru.setText("Refresh");
        refreshGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshGuruActionPerformed(evt);
            }
        });

        tambahGuru.setText("Tambah");
        tambahGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahGuruActionPerformed(evt);
            }
        });

        hapusGuru.setText("Hapus");
        hapusGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusGuruActionPerformed(evt);
            }
        });

        editGuru.setText("Edit");
        editGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editGuruActionPerformed(evt);
            }
        });

        tutupGuru.setText("Tutup");
        tutupGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupGuruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cariGuru))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tutupGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refreshGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tambahGuru)
                                    .addComponent(hapusGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCariguru, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCariguru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariGuru))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refreshGuru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tambahGuru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusGuru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editGuru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(tutupGuru))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tutupGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupGuruActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_tutupGuruActionPerformed

    private void refreshGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshGuruActionPerformed
        // TODO add your handling code here:
        tampilGuru();
    }//GEN-LAST:event_refreshGuruActionPerformed

    private void tblGuruComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblGuruComponentShown
        // TODO add your handling code here:
        tampilGuru();
    }//GEN-LAST:event_tblGuruComponentShown

    private void tambahGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahGuruActionPerformed
        // TODO add your handling code here:
        tambahGuru tambah = new tambahGuru();
        tambah.setVisible(true);
    }//GEN-LAST:event_tambahGuruActionPerformed

    private void hapusGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusGuruActionPerformed
        // TODO add your handling code here:
        hapusGuru hapus = new hapusGuru();
        hapus.setVisible(true);
    }//GEN-LAST:event_hapusGuruActionPerformed

    private void editGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editGuruActionPerformed
        // TODO add your handling code here:
        editGuru edit = new editGuru();
        edit.setVisible(true);
    }//GEN-LAST:event_editGuruActionPerformed

    private void cariGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariGuruActionPerformed
        // TODO add your handling code here:
        Object[] row = {"NIP", "Nama Lengkap"}; 
        DefaultTableModel tabmodel = new DefaultTableModel(null,row);
        tblGuru.setModel(tabmodel);
        koneksi sambung = new koneksi();
        try{
            String sql = "SELECT nip,nama_guru FROM guru WHERE nip LIKE '%" 
                    +txtCariguru.getText()+ "%'" +"or nama_guru LIKE '%" +txtCariguru.getText()+ "%'";
            ResultSet res = sambung.stat.executeQuery(sql);
            while(res.next()){
                String nip = res.getString("nip");
                String nama_guru = res.getString("nama_guru");
                String[] data = {nip,nama_guru};
                tabmodel.addRow(data);
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Koneksi Gagal "+e.toString());
        }
    }//GEN-LAST:event_cariGuruActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariGuru;
    private javax.swing.JButton editGuru;
    private javax.swing.JButton hapusGuru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshGuru;
    private javax.swing.JButton tambahGuru;
    private javax.swing.JTable tblGuru;
    private javax.swing.JButton tutupGuru;
    private javax.swing.JTextField txtCariguru;
    // End of variables declaration//GEN-END:variables
}
